language: node_js
node_js:
  - "10"
before_script:
  - npm install -g codecov
  - mkdir coverage
  - tsc
after_success:
  - cat ./coverage/coverage-final.json
  - codecov --file="./coverage/coverage-final.json"
